import React, { useState } from "react";

interface DisplayProps {
  myBool: boolean;
  myTaskNum: number;
  addNums: (num1: number, num2: number) => number;
  myArray: string[];
}

const Display = ({ myBool, myTaskNum, addNums, myArray }: DisplayProps) => {
  const [result, setResult] = useState<number | undefined>(undefined);

  const handleClick = () => {
    const sum = addNums(9, 10);
    setResult(sum);
  };

  return (
    <div>
      <h1>TypeScript Props Displayed</h1>
      <ul>
        <li>{myBool === false ? "False value generated by boolean" : ""}</li>
        <li>{myTaskNum}</li>
      </ul>
      <ul>
        {myArray.map((num) => {
          return <li key={num}>{num}</li>;
        })}
      </ul>
      <button onClick={handleClick}>Click me</button>
      <div>{result !== undefined ? `Result: ${result}` : ""}</div>
    </div>
  );
};

export default Display;
